# Generated by Django 3.2.5 on 2021-08-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_chatgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
